# Generated by Django 2.0.2 on 2019-06-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('essay', models.CharField(max_length=20000)),
                ('wordcount', models.CharField(max_length=50)),
                ('spellcheck', models.CharField(max_length=50)),
                ('grammercheck', models.CharField(max_length=50)),
                ('error', models.CharField(max_length=50)),
                ('grade',models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EssayData',
            },
        ),
    ]
