# Generated by Django 2.0.2 on 2019-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_essaydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'HTMLData',
            },
        ),
    ]
