# Generated by Django 2.2.2 on 2019-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_htmldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaydata',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
