# Generated by Django 2.2.2 on 2019-06-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190621_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
