# Generated by Django 2.2.2 on 2019-06-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaydata',
            name='articlecheck',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaydata',
            name='timetaken',
            field=models.CharField(default=55, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essaydata',
            name='totaltime',
            field=models.CharField(default=55, max_length=50),
            preserve_default=False,
        ),
    ]
