# Generated by Django 2.2.2 on 2019-06-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190623_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'GiveTake',
            },
        ),
    ]
