# Generated by Django 2.2.2 on 2019-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_givetake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givetake',
            name='starttime',
            field=models.IntegerField(max_length=100),
        ),
    ]
