# Generated by Django 2.2.2 on 2019-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190630_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givetake',
            name='starttime',
            field=models.CharField(max_length=100),
        ),
    ]
