# Generated by Django 2.2.2 on 2019-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190630_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('essay', models.CharField(max_length=20000)),
                ('wordcount', models.CharField(max_length=50)),
                ('spellcheck', models.CharField(max_length=50)),
                ('grammercheck', models.CharField(max_length=50)),
                ('articlecheck', models.CharField(max_length=50)),
                ('error', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('totaltime', models.CharField(max_length=50)),
                ('timetaken', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ScoreData',
            },
        ),
    ]
