# Generated by Django 2.2.2 on 2019-07-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190703_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoredata',
            old_name='Trained_Data_result',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='scoredata',
            old_name='Email',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='scoredata',
            old_name='Word_Count',
            new_name='wordcount',
        ),
    ]
