# Generated by Django 2.2.2 on 2019-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cohessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaydata',
            name='para_phrasing',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoredata',
            name='para_phrasing',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
