# Generated by Django 2.2.3 on 2019-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190709_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SI', models.CharField(max_length=100)),
                ('Question_type', models.CharField(max_length=100)),
                ('Question', models.CharField(max_length=50)),
                ('Answer', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'QuestionData',
            },
        ),
    ]
