# Generated by Django 2.2.3 on 2019-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_questiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohessiondata',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
